version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana-volume:/var/lib/grafana
  
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
        INFLUXDB_DB: KuzvecovDB
        INFLUXDB_ADMIN_USER: admin
        INFLUXDB_ADMIN_PASSWORD: 12345
    volumes:
      - ./influxdb-volume:/var/lib/influxdb